spring:
  http:
    encoding:
      enabled: true
      force: true
  application:
    name: Noticeboard

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Noticeboard?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: "*seoksm1017*"

  jwt:
    secret: dlstoddmsgksqjsQnsdlslchljsdmfekgotkfwkvhrlgkwlakfwk

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        #show_sql: true

server:
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8

logging:
  level:
    root: INFO  # 기본 로그 레벨은 INFO로 설정
    com.springboot.noticeboard: DEBUG  # 필요한 패키지만 DEBUG로 설정
    org.hibernate.SQL: INFO  # Hibernate의 SQL 로그를 INFO로 제한, DEBUG
    org.hibernate.type: OFF  # Hibernate 타입 로그는 끔 (너무 상세할 수 있음), TRACE

#  file:
#    name: logs/noticeboard.log
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
